const UserActionType = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	GOOGLE_SINGIN_START: "GOOGLE_SINGIN_START",
	GOOGLE_SINGIN_SUCCESS: "GOOGLE_SINGIN_SUCCESS",
	GOOGLE_SINGIN_FAILURE: "GOOGLE_SINGIN_FAILURE",
	EMAIL_SINGIN_START: "EMAIL_SINGIN_START",
	EMAIL_SINGIN_SUCCESS: "EMAIL_SINGIN_SUCCESS",
	EMAIL_SINGIN_FAILURE: "EMAIL_SINGIN_FAILURE",
};

export default UserActionType;